# Generated by Django 4.2.3 on 2023-07-28 01:02

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefix", models.CharField(max_length=6)),
                ("name", models.CharField(max_length=128)),
                ("shortname", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identity_number", models.IntegerField(unique=True)),
                ("description", models.TextField(max_length=500)),
                ("name", models.CharField(max_length=256)),
                ("creator", models.CharField(max_length=128)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("manufacturer", models.CharField(max_length=256)),
                ("mfg_part_number", models.CharField(max_length=256)),
                (
                    "design_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending"),
                            ("RETIRED", "Retired"),
                            ("OBSOLETE", "Obsolete"),
                            ("OTHER", "Other"),
                        ],
                        default="ACTIVE",
                        max_length=36,
                    ),
                ),
                ("sellable", models.BooleanField()),
                ("product_line", models.CharField(max_length=128)),
                ("longname", models.CharField(max_length=256)),
                ("part_number", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="PartType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typename", models.CharField(max_length=128)),
                ("shortname", models.CharField(max_length=16)),
                ("typecode", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="VendorPartInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=256)),
                ("order_number", models.CharField(max_length=256)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="PartResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("url", models.URLField()),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PartsRegister.part",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="part",
            name="part_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="PartsRegister.parttype"
            ),
        ),
        migrations.CreateModel(
            name="ElectroMechPartInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degild", models.BooleanField(verbose_name="De-Gild")),
                ("pretin", models.BooleanField(verbose_name="Pre-Tin")),
                ("reball", models.BooleanField(verbose_name="Re-Ball")),
                ("pasted", models.BooleanField(verbose_name="Pasted")),
                ("staked", models.BooleanField(verbose_name="Staked")),
                ("polarity", models.CharField(max_length=256)),
                ("material", models.CharField(max_length=256)),
                ("power_mW", models.IntegerField(verbose_name="Power mW")),
                ("temp", models.IntegerField(verbose_name="Temp (ppm/dC)")),
                ("temp_min", models.IntegerField()),
                ("temp_max", models.IntegerField()),
                ("tolerance", models.IntegerField(verbose_name="Tolerance (+/- %)")),
                ("value", models.IntegerField()),
                ("footprint", models.CharField(max_length=256)),
                ("voltage", models.IntegerField()),
                ("quality", models.CharField(max_length=256)),
                ("measurement_unit", models.CharField(max_length=256)),
                ("purchase_unit", models.CharField(max_length=256)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PartsRegister.part",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("identity_number", models.IntegerField()),
                ("description", models.CharField(max_length=256)),
                ("longname", models.CharField(max_length=262)),
                ("author", models.CharField(max_length=128)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("document_number", models.CharField(max_length=16)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PartsRegister.documenttype",
                    ),
                ),
            ],
        ),
    ]
