# Generated by Django 4.2.3 on 2023-07-28 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PartsRegister", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="created_date",
            field=models.DateField(auto_now_add=True, verbose_name="Created On"),
        ),
        migrations.AlterField(
            model_name="part",
            name="creator",
            field=models.CharField(max_length=128, verbose_name="Creator"),
        ),
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="part",
            name="design_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("PENDING", "Pending"),
                    ("RETIRED", "Retired"),
                    ("OBSOLETE", "Obsolete"),
                    ("OTHER", "Other"),
                ],
                default="ACTIVE",
                max_length=36,
                verbose_name="Design Status",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="identity_number",
            field=models.IntegerField(unique=True, verbose_name="Identity Number"),
        ),
        migrations.AlterField(
            model_name="part",
            name="manufacturer",
            field=models.CharField(max_length=256, verbose_name="Manufacturer"),
        ),
        migrations.AlterField(
            model_name="part",
            name="mfg_part_number",
            field=models.CharField(max_length=256, verbose_name="MFG Part Number"),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="part",
            name="part_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="PartsRegister.parttype",
                verbose_name="Part Type",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="product_line",
            field=models.CharField(max_length=128, verbose_name="Product Line"),
        ),
        migrations.AlterField(
            model_name="part",
            name="sellable",
            field=models.BooleanField(verbose_name="Sellable"),
        ),
    ]
