# Generated by Django 4.2.3 on 2023-07-28 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PartsRegister", "0002_alter_part_created_date_alter_part_creator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpartinfo",
            name="parent",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="PartsRegister.part",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="document_number",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="document",
            name="longname",
            field=models.CharField(default="", max_length=262),
        ),
        migrations.AlterField(
            model_name="part",
            name="created_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Created On"
            ),
        ),
    ]
