# Generated by Django 4.2.3 on 2023-07-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("PartsRegister", "0004_remove_vendorpartinfo_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpartinfo",
            name="parent",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="PartsRegister.part",
            ),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="footprint",
            field=models.CharField(max_length=256, verbose_name="Footprint"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="measurement_unit",
            field=models.CharField(max_length=256, verbose_name="Measurement Unit"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="purchase_unit",
            field=models.CharField(max_length=256, verbose_name="Purchase Unit"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="quality",
            field=models.CharField(max_length=256, verbose_name="Quality"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp",
            field=models.IntegerField(verbose_name="Temperature (ppm/dC)"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp_max",
            field=models.IntegerField(verbose_name="Temperature (max)"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp_min",
            field=models.IntegerField(verbose_name="Temperature (min)"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="value",
            field=models.IntegerField(verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="voltage",
            field=models.IntegerField(verbose_name="Voltage"),
        ),
    ]
