# Generated by Django 4.2.3 on 2023-07-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PartsRegister", "0005_vendorpartinfo_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electromechpartinfo",
            name="profile_name",
            field=models.CharField(
                default="", max_length=256, verbose_name="Profile Name"
            ),
        ),
        migrations.AddField(
            model_name="partresource",
            name="description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="Temperature (ppm/dC)"
            ),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp_max",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="Temperature (max)"
            ),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="temp_min",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="Temperature (min)"
            ),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="tolerance",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="Tolerance (+/- %)"
            ),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="voltage",
            field=models.DecimalField(
                decimal_places=3, max_digits=8, verbose_name="Voltage"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="longname",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="part",
            name="part_number",
            field=models.CharField(default="", max_length=16),
        ),
    ]
