# Generated by Django 4.2.3 on 2023-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PartsRegister", "0006_electromechpartinfo_profile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="degild",
            field=models.BooleanField(default=False, verbose_name="De-Gild"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="pasted",
            field=models.BooleanField(default=False, verbose_name="Pasted"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="pretin",
            field=models.BooleanField(default=False, verbose_name="Pre-Tin"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="reball",
            field=models.BooleanField(default=False, verbose_name="Re-Ball"),
        ),
        migrations.AlterField(
            model_name="electromechpartinfo",
            name="staked",
            field=models.BooleanField(default=False, verbose_name="Staked"),
        ),
    ]
